# Generated by Django 4.0.3 on 2022-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_head_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='commentPost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commentUser',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_category',
            new_name='postCategory',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categoryThrough',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post',
            new_name='postThrough',
        ),
        migrations.RemoveField(
            model_name='post',
            name='news_type',
        ),
        migrations.AddField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('AR', 'статья'), ('NW', 'новость')], default='AR', max_length=2),
        ),
    ]
